// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_cTb2XqstnBalEfu_Il_QZk_lKqRuUk',
    appId: '1:93919527769:web:e5f83416a0e660cc6e8b01',
    messagingSenderId: '93919527769',
    projectId: 'e-learning-7351c',
    authDomain: 'e-learning-7351c.firebaseapp.com',
    storageBucket: 'e-learning-7351c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_cTb2XqstnBalEfu_Il_QZk_lKqRuUk',
    appId: '1:93919527769:android:54adb7d81363d80aa38248',
    messagingSenderId: '93919527769',
    projectId: 'e-learning-7351c',
    storageBucket: 'e-learning-7351c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa_cTb2XqstnBalEfu_Il_QZk_lKqRuUk',
    appId: '1:93919527769:web:64e4874f9b624d326e8b01',
    messagingSenderId: '93919527769',
    projectId: 'e-learning-7351c',
    authDomain: 'e-learning-7351c.firebaseapp.com',
    storageBucket: 'e-learning-7351c.firebasestorage.app',
  );
}
